# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8463ed8a41d6680b575850a4e4503e97e6321bbdaab55adb881303717a6f022738a4a765c699a08667c4971f4d99e639f32bb0ba070bcce32bbd86847b2ccfe7

test:
  secret_key_base: 6f503ee301b97c6690d10181e29cca1f907637ebbde4622033824ee9e270fb0eea57e4c1fc9a0d1b860fa8459e98498c70ed32048888284a57f07d8e8861a12b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
